---

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - id: winlibs
        uses: bwoodsend/setup-winlibs-action@master

      - run: ls ${{ steps.winlibs.root }}
      - run: ls ${{ steps.winlibs.bin }}
      - run: where gcc
